version: "3.7"

services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres-db
    volumes:
      - ./DB:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    dns:
      - 8.8.8.8
      - 8.8.4.4

  backend:
    build: ./server
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgres://postgres:admin@db:5432/postgres-db'
      PORT: 5000
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
      - ./server/uploads/labs:/server/uploads/labs
      - ./server/uploads/submissions:/server/uploads/submissions
      - ./server/logs:/server/logs
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: npm run dev